POST http://localhost:7000/api/v1/product/create
Content-Type: application/json

{
"name":"Shampoo",
"price":150,
"description": "Haircare product",
"quantity" : 8
}
###
GET http://localhost:7000/api/v1/product/all

###
POST http://localhost:7000/api/v1/product/create
Content-Type: application/json

{
"name":"Kitkat",
"price":20,
"description": "Chocolate",
"quantity" : 2
}

###

PATCH http://localhost:7000/api/v1/product/edit/613dae4d6e6b812646085f99
Content-Type: application/json

{   "name" : "Hersheys"
}

###

DELETE http://localhost:7000/api/v1/product/delete/613dade56e6b812646085f96